image: php:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - apt-get update -yqq
    - apt-get install -yqq git unzip libpng-dev libjpeg-dev libfreetype6-dev libzip-dev
    - docker-php-ext-configure gd --with-freetype --with-jpeg
    - docker-php-ext-install gd pdo pdo_mysql zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cp .env.example .env
    - composer update
    - composer install --no-interaction

test:
  stage: test
  script:
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate --force --seed
    - vendor/bin/phpunit --coverage-text --colors=never
